server.port=8080
server.address=0.0.0.0

# Local SQLite Database Path
spring.datasource.url=jdbc:sqlite:${user.home}/.pos_app/pos_local_db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.application.name=pos-backend

# ==========================================
# CLOUD SYNC CONFIGURATIONS (Dev Client)
# ==========================================
pos.cloud.api.base-url=https://pos-cloud-backend-pv4k.onrender.com
pos.terminal.id=POS-TERM-01
pos.terminal.secret-key=MySecUr3P0sK3y@2026!